# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Guillaume's Blog
paginate:         1
baseurl:          /
author:
  name:           Guillaume Lobet
  url:            https://twitter.com/guillaumelobet
  email:          guillaume.lobet@ulg.ac.be

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/guillaumelobet/guillaumelobet.github.io/
  
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
